version: '2.1'

services:

  consul:
    image: progrium/consul:latest
    command: -server -bootstrap -ui-dir /ui
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8500 || exit 1"]
      interval: 5s
      retries: 10
    ports:
      - 8054:8500
    expose:
      - 53
      - 8300
      - 8301
      - 8302
      - 8400
      - 8500
    dns:
      - 127.0.0.1
    networks: 
    - default
  
  nginx-lb:
    build: nginx/
    depends_on:
      consul:
        condition: service_healthy
    ports:
      - 8050:8001
      - 8051:8000
      - 8052:8443
      - 8053:8444
    expose:
      - 8000
      - 8443
      - 8001
      - 8444
    links:
      - consul:consul
    command: >
        /bin/containerpilot
        -config file:///etc/containerpilot/containerpilot.json
        nginx -g "daemon off;"
  
  kong-database:
    image: postgres:10
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  kong-migration:
    image: kong
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    command: kong migrations up
  
  kong:
    build: kong/
    container_name: kong
    depends_on:
      kong-database:
        condition: service_healthy
      kong-migration:
        condition: service_started  
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001        
    expose:
      - 8000
      - 8001
      - 8443
      - 8444
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8000 || exit 1"]
      interval: 5s
      retries: 10
    restart: on-failure

  konga:
    image: pantsel/konga:next #(or latest)
    container_name: konga
    depends_on:
      - kong
    ports:
      - 8055:1337
    environment:
    - KONGA_SEED_USER_DATA_SOURCE_FILE=/run/secrets/konga_user_seed
    links:
      - mongo:db
      - kong:kong
    environment:
      - DB_ADAPTER=mongo
      - DB_HOST=mongo
      - DB_DATABASE=konga
      - NODE_ENV=development
    restart: on-failure
  
  mongo:
    image: mongo
    volumes:
      - $HOME/persistent/mongodb:/data/db
    ports:
      - 27017:27017
    dns:
      - 127.0.0.1

networks: 
  default:
    driver: bridge